# render.yaml

services:
  - name: ytdlp4u
    type: web
    env: docker
    dockerfilePath: Dockerfile
    autoDeploy: true
    plan: free
    envVars:
      - key: BASE_URL
        value: https://your-app.onrender.com
